baseurl = "/"
languageCode = "br"
defaultContentLanguage = "br"
theme = "hello-friend"
paginate = 5
hrefTargetBlank = true
enableRobotsTXT = true
enableInlineShortcodes = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = true
    socialShare = true ## mostrar o social share
  author = "Valdecir Carvalho"
  authorImage = "/img/valdecir.png"
  logo_1 = "/img/veeam-vanguard-logo.png"
  logo_2 = "/img/vmware-vexpert-logo.png" 
 
[Author]
  name = "Some Person"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  facebook = "username"
  github = "valdecircarvalho"
  gitlab = "username"
  bitbucket = "username"
  twitter = "@homelaber"
  reddit = "username"
  linkedin = "valdecircarvalho"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "vcarva"
  500px = "username"
  codepen = "username"
  mastodon = "url"
  kaggle = "username"
  weibo = "username"
  slack = "username"

[blackfriday]
  angledQuotes = true
  hrefTargetBlank = true


[taxonomies]
series = "series"
category = "categories"
tag = "tags"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[languages]
  [languages.br]
    title = "Blog Homelaber Brasil"
    subtitle = "Blog Homelabler Brasil | Home lab· Infraestrutura de TI· Virtualização· Cloud Computing · DevOps | Blog sobre Virtualização, Infraestrutura de TI, Cloud Computing e DevOps escrito em Português. Criado e editado por Valdecir Carvalho"
    keywords = "Blog, Infraestrutura, TI Corporativa, Virtualização, Veeam, Backup, Cloud, Cloud Computing, Cloud Native, Homelab"
    copyright = "2016-2019 - Homelaber Brasil - Valdecir Carvalho"
    menuMore = "Mostrar mais"
    writtenBy = " "
    readMore = "Continue lendo"
    readOtherPosts = "Leia outros posts"
    newerPosts = "Novos posts"
    olderPosts = "Posts antigos"
    minuteReadingTime = "min lendo"
	wordCount = "palavras"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"

    [languages.br.params.logo]
      logoText = "Homelaber Brasil"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.br.menu]
      [[languages.br.menu.main]]
        identifier = "about"
        name = "sobre"
        url = "/sobre/"
		weight = 2
      [[languages.br.menu.main]]
        identifier = "arquivo"
        name = "arquivo"
        url = "/archive/"
		weight = 1
#     [[languages.br.menu.main]]
#        identifier = "meu-homelab"
#        name = "meu homelab"
#        url = "/homelab"
#		weight = 3
#	  [[languages.br.menu.main]]
#        identifier = "github"
#        name = "github"
#        url = "https://github.com/valdecircarvalho/"
#		weight = 4
#	  [[languages.br.menu.main]]
#        identifier = "twitter"
#        name = "@homelaber"
#        url = "https://twitter.com/homelaber"
#		weight = 5
