baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[taxonomies]
series = "series"

#[blackfriday]
#hrefTargetBlank = true

[languages]
  [languages.en]
    title = "Blog Homelaber Brasil | "
    subtitle = "Homelab·Infraestrutura de TI· Cloud Computing· DevOps"
    keywords = ""
    copyright = "2016-2019 - Homelaber Brasil - Valdecir Carvalho"
    menuMore = "Mostrar mais"
    writtenBy = ""
    readMore = "Continue lendo"
    readOtherPosts = "Leia outros posts"
    newerPosts = "Novos posts"
    olderPosts = "Posts antigos"
    minuteReadingTime = "min lendo"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"

    [languages.en.params.logo]
      logoText = "Homelaber Brasil"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "sobre"
        url = "/sobre"
		weight = 2
      [[languages.en.menu.main]]
        identifier = "arquivo"
        name = "arquivo"
        url = "/archive"
		weight = 1
#     [[languages.en.menu.main]]
#        identifier = "meu-homelab"
#        name = "meu homelab"
#        url = "/homelab"
#		weight = 3
	  [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/valdecircarvalho/"
		weight = 4
	  [[languages.en.menu.main]]
        identifier = "twitter"
        name = "@homelaber"
        url = "https://twitter.com/homelaber"
		weight = 5
